default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_DB_USER") %>
  password: <%= ENV.fetch("POSTGRES_DB_PASSWORD") %>

production:
  <<: *default
  database: blog

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test
